services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - expenses-app

  expenses-app:
    build: .
    container_name: expenses-app
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expenses_db
      SPRING_DATASOURCE_USERNAME: dave
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: expenses_db
      POSTGRES_USER: dave
      POSTGRES_PASSWORD: secret
    cpu_count: 1
    mem_reservation: 2g
    ports:
      - "5432:5432"
